spring:
  application:
    name: BuckProdRestHw
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/rest_hw
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver